spring:
  profiles:
    include: db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 500
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false